# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

df = pd.read_csv('Tamil_first_ready_for_sentiment.csv', sep='\t')
df.rename(columns = {'Negative ':'sentiment',
                              ' Enna da ellam avan seyal  Mari iruku':'comment'},
                              inplace = True)
print(df.columns)

df.head()

import string

#defining the function to remove punctuation
def remove_punctuation(text):
    
    punctuationfree="".join([i for i in text if i not in string.punctuation])
    return punctuationfree

#storing the puntuation free text
df['clean_comment']= df['comment'].apply(lambda x:remove_punctuation(x))

df.head()

df['comment_lower']= df['clean_comment'].apply(lambda x: x.lower())

#defining function for tokenization
import re
def tokenization(text):
    tokens = re.split('W+',text)
    return tokens
#applying function to the column
df['comment_tokenied'] = df['comment_lower'].apply(lambda x: tokenization(x))

df['comment_tokenied'][:5]

import nltk

nltk.download('stopwords')
stopwords = nltk.corpus.stopwords.words('english')

#defining the function to remove stopwords from tokenized text
def remove_stopwords(text):
    output= [i for i in text if i not in stopwords]
    return output

df['no_stopwords']= df['comment_tokenied'].apply(lambda x:remove_stopwords(x))

#importing the Stemming function from nltk library
from nltk.stem.porter import PorterStemmer
#defining the object for stemming
porter_stemmer = PorterStemmer()

#defining a function for stemming
def stemming(text):
  stem_text = [porter_stemmer.stem(word) for word in text]
  return stem_text

df['comment_stemmed'] = df['no_stopwords'].apply(lambda x: stemming(x))

from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
nltk.download('omw-1.4')
#defining the object for Lemmatization
wordnet_lemmatizer = WordNetLemmatizer()

#defining the function for lemmatization
def lemmatizer(text):
  lemm_text = [wordnet_lemmatizer.lemmatize(word) for word in text]
  return lemm_text

df['msg_lemmatized'] = df['no_stopwords'].apply(lambda x:lemmatizer(x))

df.head()

